### ISSUE TITLE
Requests for Workshops

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/librarycarpentry#10]
As we set out a pathway towards consolidating Library Carpentry whilst protecting the 'Carpentry' brand and not diverting time/funds from SWC/DC, we need to figure out how to manage library software skills training requests for workshops that either come via SWC/DC or from our contacts (so, via established Carpentry and from outside of Carpentry).

A starting point is to have regional contact points for this. I'll put my hand up for Europe for now. Who is willing and able to take other regions into which we have existing reach? cc @pitviper6 @weaverbel @anelda :)

**EUROPE**: @drjwbaker
**NORTH AMERICA**: @pitviper6
**AUSTRALIA**: @weaverbel 
**SOUTH AFRICA**: @ivdwalt & @erikamias

Next we need an outline workflow for how we handle requests, with an eye on both not burdening SWC/LC and not getting too procedural too soon. Something light like:
- **For Requests that come through SWC/DC**: normal SWC/DC process; LC contact looped in; LC contact fields questions/queries from requester about LC modules; requester tells SWC/DC about what modules they want; workshop agreed with SWC/DC in normal way; if LC content used, LC contact seeks/suggests instructor from LC community who may be able to join the workshop (but there is nothing saying that they have to!).
- **For Requests that came to LC**: request forwarded to LC contact; LC contact finds out what they want/what funds they have and either a) seeks/suggests instructor from LC community who may be able to join the workshop (may be self!) _or_ b) steers workshop towards standard SWC/DC request process above; if a) SWC/DC made aware of workshop, SWC/DC suggests instructor if/as appropriate, workshop logged.

Discuss..

_see http://pad.software-carpentry.org/library-carpentry for more info._

**Comment by pitviper6** [comment]
I'd be happy to be the North American point person. I just wrote something about that over in the other issue!  https://github.com/data-lessons/librarycarpentry/issues/6

**Comment by drjwbaker** [comment]
@pitviper6 Brilliant!

**Comment by weaverbel** [comment]
Sign me up for Australia-wrangling. ;-)

**Comment by tracykteal** [comment]
Thanks for this. I'll talk with @jduckles about what we can do on our end, because it has been SWC that has been running workshops for librarians.

**Comment by weaverbel** [comment]
Ok @tracykteal I have AMY access so I can grab the ones I see come in for Australia from there. If others come in directly, I'll put them into AMY? I've done that before.

**Comment by tracykteal** [comment]
I think we need to figure out if SWC/DC can officially coordinate these workshops. Part of the discussion today was figuring out the relationship between Library Carpentry and SWC/DC, and what the Library Carpentry community wants to do. So far we've been teaching SWC for librarians, and changing out some modules, but we haven't been offering 'Library Carpentry' as far as I know.

**Comment by weaverbel** [comment]
Definitely a discussion for SWC/DC SC etc then @tracykteal

**Comment by anelda** [comment]
Hi all,

Thanks and well done on moving this initiative forward with so much
enthusiasm!  Apologies for not responding earlier.  I hope to identify
someone in the South African Library community who could play this role as
I think my own contributions as a non-librarian might not in the long run
be what you/the library community needs.

Please keep me in the loop for now as we try to find our SA representative.

Anelda

**Comment by drjwbaker** [comment]
@anelda Thanks for this. Let us know if/when you've found someone!
jb

**Comment by anelda** [comment]
Hi all, I'd like to introduce @ivdwalt and @erikamias who have agreed to act as the South African representatives. I am not saying good bye to LC, just think it's time someone from the Library community joins this conversation :-). I trust you will enjoy working with them. @ivdwalt & @erikamias, welcome to LC...

**Comment by cmacdonell** [comment]
Welcome @ivdwalt and @erikamias! I fondly remember working with you in Pretoria :)

**Comment by ivdwalt** [comment]
Hi All, we look forward to making our contributions and move forward with LC in South Africa. 

Isak

**Comment by drjwbaker** [comment]
Excellent! @ivdwalt and @erikamias: any questions? In the first instance, we imagine local contact points will help us manage requests for workshops and/or info on LC that come to us or via Software/Data Carpentry. Have either of you taken the Software Carpentry Instructor Training course? https://swcarpentry.github.io/instructor-training/

**Comment by weaverbel** [comment]
Welcome @ivdwalt and @erikamias ! Do you know you can chat to a whole range of Library Carpenters in our ongoing chatroom? Please feel free to come in - it has all the chat since the sprint !
https://gitter.im/weaverbel/LibraryCarpentry

**Comment by erikamias** [comment]
Hello All :)

I haven't attended the Software Carpentry Instructor training yet but @anelda announced at SWC at PyCon that there will most likely be an instructor training course soon which I would like to attend? I have been lurking on the LC Gitter for some time... I will send you my questions soon!

**Comment by erikamias** [comment]
Some questions to start with:

Are the LC SA python sessions going to be pitched at the same level as the SWC Python sessions? 

If we do offer LC Python sessions is it possible to have one session where (after learning Bash Shell) you do a more basic/introductory python session and then a second session doing more practical work and spending more time on data-analysis/visualisation?

Can part of the lesson plan/setup show MAC/Windows/Linux users the commands to access/revert to Python 2. so that they can easily access it after the WKSP? The free online teaching materials ush as "learn python the hard way" teach using python 2 and it would be one less obstacle for those who want to continue their training after the workshop?

Will there be certificates/letters of attendence offered to LC in South Africa? Some institutions require some proof of event and attendance as this type of training counts towards employee development?

**Comment by drjwbaker** [comment]
@erikamias:

- on instructor training: no hurry on this. We're aiming to ensure that there are some LC-affiliated folks that go through the training in the next 12 months, rather than it be a rule that every workshop includes a trained instructor (see note on this at http://librarycarpentry.github.io/about/). Getting trained is still on my todo list, for example.
- on Python: we don't have a Python lesson but that doesn't mean we shouldn't rather that we need the library specific case studies to justify it.
- on proof of attendance: we can do that. I made a simply template for the first LC in London as some people asked. Does anyone know how SWC/DC handle this? No point reinventing the wheel et cetera!

**Comment by weaverbel** [comment]
@drjwbaker @erikamias Re attendance certs - SWC don't do that as far as I know, but I just make one if someone needs it.

**Comment by tracykteal** [comment]
I have a LaTex template for letters of completion when they're requested. The pdf looks like this. Happy to share the template!

[template-workshop-participation.pdf](https://github.com/data-lessons/librarycarpentry/files/534847/template-workshop-participation.pdf)

**Comment by gvwilson** [comment]
We haven't done attendance certificates in the past because we want the 
certificate to mean something more than "I sat through this", and we 
haven't had the resources to do some sort of final assessment.  It's on 
our wishlist, though...

**Comment by weaverbel** [comment]
@gvwilson I just do an 'I sat through it' certificate for people with bossy workplaces - just a tick in the box thing that says nothing more than that they came and the dates they came.

**Comment by ostephens** [comment]
@drjwbaker @erikamias there is a Library Carpentry Python lesson in the repo https://github.com/data-lessons/library-python which has only recently been added by @c-martinez 

This is based on the Data Carpentry Ecology Python lesson http://www.datacarpentry.org/python-ecology-lesson/ but has been adapted to use the same data set as the Library Carpentry SQL and OpenRefine lessons.

There was some discussion of the lesson in the Gitter chatroom on Sept 28/29

**Comment by drjwbaker** [comment]
@tracykteal Thanks much! Basing ours on that seems sensible
@weaverbel @gvwilson From what I've observed, library folk (at least though who came to the UK workshop) often need certificates as paperwork that proves that professional development happened.

**Comment by drjwbaker** [comment]
@ostephens  @erikamias Okay, I totally missed that! I'll blame the start of term for the umpteenth time this term :)

**Comment by ivdwalt** [comment]
@drjwbaker @weaverbel I am catching up with the thread (had a server crash that needed attention). My questions are in line with that of @erikamias. I have not completed any of the instructors training but would like to do so asap.

**Comment by drjwbaker** [comment]
https://amy.software-carpentry.org/workshops/request_training/

**Comment by pitviper6** [comment]
Also posted in LC Gitter, but figured I'd put it here as well:
Hey everybody! This is my last day at UC San Diego - starting Monday I'll be working for a consulting firm as a Data Production Manager. It's an exciting opportunity (massive datasets, lots of normalization/taxonomizing, etc), but it does mean that I'll no longer have the academic lifestyle (i.e., time). I had volunteered to be North American coordinator for LC workshop requests through DC and SWC, but I'm going to have to pass that on to someone else. Anybody interested?

I'll still be a maintainer of the LC Open Refine lesson, unless someone is rabidly interested in taking that over as well. I was in the middle of breaking down the basics I lesson into three smaller chunks, and I intend to finish that up, but am not sure as of yet just how much time I'm going to have moving forward. HOpefully enough to remain an active part of the LC community!

**Comment by ccronje** [comment]
@pitviper6 Congratulations! 😃  and thank you so much for all your help here! I'd like to assist with your work on OpenRefine.

Just so folks here know, next month I'll be teaching (& learning as I go) the 4 core LC lessons to a group of 5 people in my library (4x librarians and 1x IT). They're really keen to see what it's all about and potentially teach it. It's been trickier than I thought trying to do this in between everyone's BAU workloads - but the spirit is there and we'd like to roll out at least OpenRefine to the greater library early 2017. This means we'll be quite focused on that lesson so should be able to contribute back to the content.

**Comment by drjwbaker** [comment]
@pitviper6 Once again, my congratulations and thank you so much for your hard work on and enthusiasm towards Library Carpentry.

@ccronje Awesome! Always good to hear of folks passing the skills they have learnt on! Do add this session to the master list https://docs.google.com/spreadsheets/d/17EMzgODvvX4qnfpNvHkdIi3VzZp3r_sdYHld1YrpB-A/edit#gid=0
