### ISSUE TITLE
LibCarpentry twitter

### ISSUE THREAD

**Issue by weaverbel** [data-lessons/librarycarpentry#12]
The [@LibCarpentry](https://twitter.com/LibCarpentry) twitter is now live - thanks to John Chodacki. 

Please follow and also tweet the news.

John has emailed me the password for the account - please either email me or John to get the password or just ping me in the chatroom to send it. I am weaverbel AT gmail.com. I'll leave it up to John to put his email on here.

**Comment by drjwbaker** [comment]
@jezcope Did you setup an LC whilst doing the analytics or the request form? We could use that...

**Comment by weaverbel** [comment]
@drjwbaker I've just emailed you the pw in case anyone wants it from now - am about to go home for the day. We have 3 new people already following !

**Comment by jezcope** [comment]
@drjwbaker @weaverbel Nope, I used my own account, but ownership for both can be transferred to an LC account if someone wants to set it up.

**Comment by drjwbaker** [comment]
Okay. I vaguely recall a discussion of an LC email. But if there isn't one, let's not set one up!

**Comment by weaverbel** [comment]
The @LibCarpentry twitter is now live and @drjwbaker and I both have the credentials if anyone else wants to be a tweeter. I am now closing this issue.
