### ISSUE TITLE
2016 Workshop call judging

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/librarycarpentry#13]
The 2016 workshop call closes 16 December http://librarycarpentry.github.io/workshop-call/ We need a group of people who can agree to read through these and together make a decision by the new year. Say ay below if you can help!

**Comment by weaverbel** [comment]
It's aye from me @drjwbaker  !

**Comment by jezcope** [comment]
I'm happy to help!

**Comment by ostephens** [comment]
I'm happy to help but wondering about the criteria on which submissions will be judged?

**Comment by drjwbaker** [comment]
Starting point for criteria:
- quality of application
- value for money
- impact on library community
- value for Library Carpentry

**Comment by weaverbel** [comment]
@drjwbaker Are we going to give the whole 500 quid to one lot? Or is there room in the judging to split it between two (or more) equally worthy applicants? 500 quid sounds like a lot of money to me - maybe we could get two workshops for the money? What do other people think? Or maybe we could have a 1st, 2nd, 3rd where the best app gets 300, the runner up gets 125 and the third lot get 75? I have never had the luxury of any funding (boo hoo) to do workshops - all the SWC/LC ones I have run have been done on the smell of an oily rag so I know plain old goodwill and enthusiasm can take you a long way ... Fine if it's easier to all go to one group though.

**Comment by drjwbaker** [comment]
Depending where you are and if it costs you money to book space, £500 can go very quickly in my experience (indeed I suspect £500 wouldn't be enough for some people). We have room to go back to people and see if they can make savings. Ultimately, it is our choice. I'd like to think we can support more than one workshop financially, but we'll see who applies and what they think they need.

**Comment by weaverbel** [comment]
@drjwbaker Good point - I hadn't thought about room bookings - we get a lot of 'in kind' support working in unis.

**Comment by drjwbaker** [comment]
We do as well, I just don't like to assume that everyone does.

**Comment by drjwbaker** [comment]
@jezcope @weaverbel @ostephens @richyvk All. We've had 10 applications! I've linked you to a document for marking them (note, we have a tab each!), included within which is a link to a folder with the applications. Any problems getting access let me know.

To keep it simple, I've suggested a simple 1-5 marking scheme for the criteria above https://github.com/data-lessons/librarycarpentry/issues/13#issuecomment-260577439 I'd be grateful if you could work through them, hacking the assessment criteria as you see fit. With luck, by the end you'll have 2-3 you are passionate about supporting!

I've also added a column 'Should we try and support this with person time?'. I'd like to think we can support as many as possible. If you are willing and able to support an event with person time that we decide not to fund, please indicate as such.

On conflict of interest, judge that as you see fit. I've had lots of people contact me about hosting a workshop, so have chosen only to state a conflict with the one proposed to be held at my University. If you want to chose different criteria (you know someone, they've chatted to you about this), fine by me.

We said we'd let people know in early-Jan. I'm on leave from 7-16 January and at a conference 4-6 January, so our options are a) decide by/on 3 January b) w/c 16 January. Let me know which you'd prefer (I'm working over the Christmas period, so am happy either way). I suspect a call would be the best way to decide the 1/2 workshops we give money to, if we can fix a time zone friendly slot that works for all!

Any questions, let me know.

**Comment by weaverbel** [comment]
Hi all. I have put my preliminary ratings and comments on the spreadsheet. I might revisit though once I think about them all a bit more. My big concern is the lack of ambition with numbers - if we are going to blue 500 quid, it would be nice to see more than 15-20 people trained. I would like to see any winner open up the workshop to people nearby so numbers could potentially reach 30, or even 40. I am keenest on ones that show an interest in contributing new material or spawning new trainers. I also feel strongly that the training should be for working librarians - hence the library student one got a very big thumbs down from me - let the library school start teaching those skills ...

**Comment by richyvk** [comment]
Hi. I've also added my ratings to the spreadsheet, and a few comments that hopefully clarify my decisions.

A couple of things I was kind of unclear about - firstly the column 'Target audience HE' - why was this included - is LC somehow aimed primarily at HE? I couldn't find anything to say it is. Anyway, I haven't included that in my considerations.

I note at least one of the proposals was to teach non-LC content - e.g. SWC content. I know there is overlap but I marked down of this a bit because it seemed to be not something LC should put money towards.

I have to respectfully disagree with Belinda about LIS students as a target audience. I think it's probably a good thing, if the library school can't teach it on their own.

That leads me to my final confusion, it seems like a lot of proposals are asking for funding to get an LC person to run the workshop. Correct me if I'm wrong but it is not a requirement to have an LC certified instructor to run an LC course, right? Isn't the idea for anyone to do it if they feel comfortable doing so?

Anyway, taking all that into account I hope my assessments will aid the decision. Being an extreme LC newbie I am conscious that others will have very different scoring based on their greater knowledge and understanding of LC's goals.

**Comment by drjwbaker** [comment]
@weaverbel Kinda agree on numbers, but I'm minded that £500 doesn't go that far (in the UK at least!) and that - perhaps - folks have been conservative because they've tried to balance instructor/helper/attendee numbers.

@richyvk 

- target audience. I merely added that because we are very HE focused at present (by accident rather than design) and I wanted to make a distinction between those who sought to connect with wider communities of librarians. Our lessons/examples could certainly benefit from reflecting the super-diversity of librarianship.
- LIS. The original run of LC filled a gap that a library school couldn't offer (City University London). I think we should be supportive of library schools but they do also need to be more proactive in their hires if they want this kind of material covered as 'core'.
- On proposals asking to fund an LC instructor to come along, see what we say at http://librarycarpentry.github.io/about/ 'What is a Workshop'. Of course anyone can use the materials and run a LC workshop, but at some stage we do need to start protecting the 'Carpentry' brand that has been generously lent to us. As we establish this will be something we have to manage carefully.

**Comment by drjwbaker** [comment]
(and of course, thank you SO MUCH!!)

**Comment by drjwbaker** [comment]
@richyvk @weaverbel @jezcope So, pending @ostephens it looks like we have one outstanding candidate. This happens also to be cheap, so we'd need to decide a) where we want the rest of the funds to go and b) which other events we'd like to support with person time. I'm on leave after today until 16 January, so perhaps we can set a chat up for 19, or 20 Jan? As we're UK and Aus based only, we should be able to find a slot that doesn't involve ridiculous hours! If we can all do on of these dates, please agree a time in my absence and ping me as I'm free all day on those days (I can also do anytime 23, 24, 26 Jan if needed). Thanks!

**Comment by ostephens** [comment]
Apologies for the delay - will do my marking today.

I can do 20th Jan pretty much any time. 23rd & 24th also work for me

**Comment by ostephens** [comment]
OK - marking complete

**Comment by drjwbaker** [comment]
Thanks Owen!

**Comment by richyvk** [comment]
@drjwbaker thanks for answering my questions :)

I'm on hols from 18 - 23 Jan, but I might be able to dial in for a chat. But in case I can't my immediate  thought would be just fund (or part fund) the 2nd place submission with the remainder funding (if that can work?).

**Comment by drjwbaker** [comment]
What about 24 Jan at 0900 UTC / 1900 AEST ? https://www.timeanddate.com/worldclock/converter.html?iso=20170124T090000&p1=136&p2=47 Or 0800 UTC if others can? I'll email @weaverbel the details.

I'd like to talk a little about what we had, no least in terms of non-funded events we might support in the future.

**Comment by jezcope** [comment]
I'm busy 9-10 next Tuesday. I usually get into the office about 08.15, but that's heavily dependent on the trains. 1000UTC/2000AEST would work for me though. (All times UTC)

**Comment by weaverbel** [comment]
Hi all
Good for me - do you want me to send a zoom invite or will we do a hangout? Zoom is pretty good.
1000UTC works but I can do any time that day.

**Comment by drjwbaker** [comment]
Looks like 10:00UTC/20:00AEST on 24 Jan then. @ostephens: does that work for you?

Don't know Zoom. Happy to use whatever service someone else knows to be robust!

**Comment by ostephens** [comment]
I'm currently juggling some other commitments on 24th - I'm going to have to finalise those first before I can commit to joining this call. Apologies

**Comment by richyvk** [comment]
I should be around to make that. Will be great  to chat in person :)

Richard

**Comment by ostephens** [comment]
Yes - please go ahead whether I can make it or not. Best wishes. Owen

**Comment by drjwbaker** [comment]
Okay, 10:00UTC/20:00AEST on 24 Jan it is, with me, Jez, Richard, and Belinda (plus Owen as a maybe).

If @weaverbel sets up a Zoom call, fine, otherwise I'll link a hangout here on Tuesday morning.

Our agenda is quite simple:

- agree on allocation of funds
- agree on which unfunded events we are wiling to support or recommend for support (and who might be able to help)

Looking forward to it!

**Comment by weaverbel** [comment]
Hi all - The zoom link for our meetup later is https://aarnet.zoom.us/j/666360353 - Jez, I couldn't find an email address for you but I hope you will see this. James. maybe you could forward the link to Jez?

**Comment by drjwbaker** [comment]
Thanks @weaverbel. I've forwarded to Jez.

**Comment by jezcope** [comment]
:+1: Thanks @drjwbaker @weaverbel

**Comment by weaverbel** [comment]
I think we can close this one now !
