### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/librarycarpentry#15]
We have a new logo! ([vector file](https://www.dropbox.com/s/pdu8ywhswonst2w/LibraryCarpentry_Logo_Vector.ai?dl=0), [pdf](https://github.com/data-lessons/librarycarpentry/files/613599/LibraryCarpentryLogo_Draft_04.pdf))

I'll start integrating these next week around the lessons and sites next week.

Credit to [Tammy Nguyen](https://twitter.com/tammysongnguyen) for her AWESOME work (and to [Alix Keener](https://github.com/alixk) for bringing us and Tammy together!)

**Comment by drjwbaker** [comment]
Done (though it is a little small..)

**Comment by ostephens** [comment]
I've increased the width allowed for the site-avatar on https://librarycarpentry.github.io/ so the logo doesn't get shrunk.

On the Lesson pages I think we should consider having an alternative version of the logo - my suggestion is:

* Use just the 'LC' part of the logo - this would allow us to make the logo display larger without increasing the height of the navigation bar
* Some colour (at the moment it fades into the grey background of the navigation bar) - although potentially if the logo was larger this would matter less

**Comment by drjwbaker** [comment]
Cheers @ostephens 

I've changed the file at http://data-lessons.github.io/library-data-intro/ Do you know where in the template config we can change the site of site avatars? I can make the changes once I know where to make them!

**Comment by drjwbaker** [comment]
Scratch that. Found it. I think..

**Comment by drjwbaker** [comment]
How's that? http://data-lessons.github.io/library-data-intro/ Any bigger and the bar looks daft (all I've done is adjust the logo and buffer size at https://github.com/data-lessons/library-data-intro/blob/gh-pages/assets/css/lesson.scss)

**Comment by ostephens** [comment]
Just my opinion but...

I think the logo looks better with the interlocking staggered height L and C
I think 70px is as high as the bar should go - so I'd take the navbar-logo size down to 70px
I still think it probably needs some colour to stand out

Just my 2p though

**Comment by cmacdonell** [comment]
I like the staggered logo as well.  The grey logo with everything else black on http://librarycarpentry.github.io does tend to wash it out.

Rather than adding colour, what about using a larger logo and removing the text that reads "Library Carpentry"?  SWC and DC have a "banner" navbar above their logo, we could do something like that.

**Comment by drjwbaker** [comment]
Are you referring to the blue banner here https://software-carpentry.org/ @cmacdonell?

**Comment by cmacdonell** [comment]
Yes, and the wood-grain banner on http://datacarpentry.org

**Comment by weaverbel** [comment]
I am closing this as MSL wants the repo to be spick and span so it isn't confusing for sprinters when they come in. We can always re-open issues if we need to.

**Comment by drjwbaker** [comment]
Reopening for sprint. Task is to make the logo look better on all LC lesson pages, e.g. http://data-lessons.github.io/library-data-intro/

**Comment by drjwbaker** [comment]
Keeping this here as we lost the logo in the latest SWC template update. @mkuzak did you figure out why?
