### ISSUE TITLE
Adding github topics to LC lessons

### ISSUE THREAD

**Issue by jezcope** [data-lessons/librarycarpentry#16]
This week Github [announced the ability to add topics to repositories](https://github.com/blog/2309-introducing-topics) so it's worth looking at what topics we ought to add to ours.

Software Carpentry are also discussing this so we should probably attempt some kind of consistency swcarpentry/styles#130

**Comment by drjwbaker** [comment]
@jezcope Good catch? Are you monitoring the SWC discussion? If so, we should - I think - mostly do what they do with a 'library' and/or 'information science' flag somewhere.

**Comment by jezcope** [comment]
Yup, I'm keeping an eye on it. There hasn't been much discussion yet!
