### ISSUE TITLE
Sprint issues

### ISSUE THREAD

**Issue by weaverbel** [data-lessons/librarycarpentry#19]
Please use **Issues** to raise questions, report problems and other things for discussion during the sprint. Be sure to label your issue `mozsprint` so we can find these easily.

**Comment by jezcope** [comment]
I just tried, but apparently labels can only be set be repo collaborators and it seems that I'm not one!

**Comment by weaverbel** [comment]
Hi @jezcope I've invited you to be a repo man ! aka an admin here. Sing out if that doesn't work.

**Comment by jezcope** [comment]
@weaverbel Seems to have worked. Thanks!

Should we be raising surrogate `mozsprint` issues here to link to those in other repos, e.g. data-lessons/library-python#38?

**Comment by weaverbel** [comment]
@jezcope Why not? We can also link through to the repos in question from the issue. Maybe raise that in the chatroom?  I don't think we've really worked out our sprint plans fully so it is timely. I'm on the road for the next month which is why I am trying to nail this all down now.

**Comment by drjwbaker** [comment]
Closing as the sprint is over :( But look how awesome we were :)

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/mozsprint?src=hash">#mozsprint</a> by the (GitHub) numbers! 50 hours of non-stop collaboration on open projects for a healthy Internet 👏👏👏<a href="https://t.co/bsor3KNvU6">https://t.co/bsor3KNvU6</a> <a href="https://t.co/dDdNAAyv4g">pic.twitter.com/dDdNAAyv4g</a></p>&mdash; Mozilla Open Leaders (@MozOpenLeaders) <a href="https://twitter.com/MozOpenLeaders/status/870850385602326528">June 3, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
