### ISSUE TITLE
Rework Python lesson

### ISSUE THREAD

**Issue by jezcope** [data-lessons/librarycarpentry#21]
Further details and discussion over at data-lessons/library-python#38

**Comment by drjwbaker** [comment]
Issues should be assigned to @richyvk (I don't appear to have the privileges to do this!)

**Comment by drjwbaker** [comment]
Seems lots happened! From @richyvk on gitter:

> OK, I've merged most of the PRs into the Python lesson. Massive thanks to all who were super busy working on this. @elliewix was prolific :grinning: @ylja I will merge yours soon, just want to give it a read through. If anyone wants to continue working on the lesson with me now the sprint is done let me know and we can discuss :grinning:

> [https://gitter.im/weaverbel/LibraryCarpentry?at=5933d8797503e2b7060c5d7c](https://gitter.im/weaverbel/LibraryCarpentry?at=5933d8797503e2b7060c5d7c)

**Comment by drjwbaker** [comment]
Discussion should now move to lesson repos. Only issue is which lesson to take forward - https://github.com/data-lessons/library-python-intro/ or https://github.com/data-lessons/library-python or both - and where they sit within the (new) incubator process https://github.com/data-lessons/librarycarpentry/issues/22
