### ISSUE TITLE
Work on incubator lessons and process

### ISSUE THREAD

**Issue by jezcope** [data-lessons/librarycarpentry#22]
There are currently two lessons in an "incubator" phase:

- [library-webscraping](https://github.com/timtomch/library-webscraping)
- [library-spreadsheets](https://github.com/jezcope/library-spreadsheets)

They both need further development as well as being taught some more so they can be refined. We also need to make sure they are flagged up better on the website as needing further development.

**Comment by jezcope** [comment]
See also LibraryCarpentry/librarycarpentry.github.io#22

**Comment by drjwbaker** [comment]
Thanks for http://pad.software-carpentry.org/library-carpentry-incubator @jezcope 
My comments are inline.

**Comment by jezcope** [comment]
@drjwbaker Ok, there is now a [lesson list on the home page](http://librarycarpentry.github.io/#our-lessons) and a separate [our lessons page](http://librarycarpentry.github.io/lessons/) with more details about the lesson statuses and development process. To save duplication, both pages take lesson data from [`_data/lessons.yaml`](https://github.com/LibraryCarpentry/librarycarpentry.github.io/blob/master/_data/lessons.yaml).

Still to do:

- Discuss and refine process and status descriptions
- All lesson maintainers to check titles, URLs and descriptions in [`_data/lessons.yaml`](https://github.com/LibraryCarpentry/librarycarpentry.github.io/blob/master/_data/lessons.yaml)
- Probably scope for improvements to formatting too

**Comment by drjwbaker** [comment]
Looks good @jezcope. Huge improvement to what we had!
