### ISSUE TITLE
Refresh & revise Library Carpentry website

### ISSUE THREAD

**Issue by jezcope** [data-lessons/librarycarpentry#23]
The website is at http://librarycarpentry.github.io — [see `mozsprint`-tagged issues for more details](https://github.com/LibraryCarpentry/librarycarpentry.github.io/labels/mozsprint)

**Comment by drjwbaker** [comment]
@jezcope Did some work on this, focusing on incubator process https://github.com/data-lessons/librarycarpentry/issues/22 and past/forthcoming event management (I don't have a link). @jezcope: when you get a minute, could you update on the work and close for now. We can return to the website more generally at a later date.

**Comment by drjwbaker** [comment]
Also, before I forgot, we do need to make a list of all the lessons with the incubator https://github.com/data-lessons/librarycarpentry/issues/22 stamps at http://librarycarpentry.github.io/

I'm happy to do this once the incubator workflow is in place.
