### ISSUE TITLE
Improve OpenRefine lesson

### ISSUE THREAD

**Issue by jezcope** [data-lessons/librarycarpentry#26]
Plenty of issues, big and small, to get your teeth stuck into over at [data-lessons/library-openrefine](https://github.com/data-lessons/library-openrefine/issues).

**Comment by emcaulay** [comment]
I'd like to participate in helping on this topic. I have dabbled in Open Refine a little and I did take the Open Refine lesson when we hosted Library Carpentries here at UCLA (a little less than a year ago). Should I just start by doing a careful review of the lesson?

**Comment by emcaulay** [comment]
And, eeks, when I click on the link above the repo now is tagged DEPRECATED, so I'm guessing I'm already lost!

**Comment by libcce** [comment]
Hi @emcaulay, the repo has moved to https://github.com/LibraryCarpentry/lc-open-refine (but you can look through the issues here, at least for the moment). I believe @pitviper6 has had some ideas for improving this lesson.

**Comment by weaverbel** [comment]
I have also raised an issue on all the new repos to point back to where old
issues are located.

Belinda Weaver
Community and Communications Lead
The Carpentries
e: bweaver@carpentries.org | p: +61 408 841 882 | t: @cloudaus

**Comment by pitviper6** [comment]
@emcaulay Hey there! I didn't have plans for the OR lesson this sprint (I'm going to work on the intro section, especially the regex stuff), but feel free to review it and create some pull requests for any improvements you'd like to make. We're always looking for more exercises and it would be great to pull in a section showing how to reconcile Wikidata.

**Comment by emcaulay** [comment]
I apologize -- I found this tagged for mozsprint, but I didn't notice the year of jezcope's comment. So, i just thought this was for this year. my bad. still learning.

**Comment by pitviper6** [comment]
Aren't we all!

**Comment by emcaulay** [comment]
:) best way to be -- always be learning!
