### ISSUE TITLE
Create list of shell tasks for librarians

### ISSUE THREAD

**Issue by weaverbel** [data-lessons/librarycarpentry#31]
We need to create some scenarios and use cases for the shell lesson, and this could be a good sprint task.

We have counting and mining data, we have grep to find info within files, and basic shell navigation. Should we do a FOR loop? And what else? At my workshop today, people wanted specific tasks the shell can do for librarians. It would be good to create a list.

**Comment by ostephens** [comment]
Just a couple of suggestions where I've used shell scripts: 
File renaming 
Fetching files from list of URLs in a file

**Comment by weaverbel** [comment]
I agree @ostephens - batch file renaming and moving is a great one. I can work up an exercise for that - we need more 'doing' in that lesson as opposed to showing. Not sure how the fetch files thing would work - can you please tell me more?

**Comment by ccronje** [comment]
A use case that came up recently was creating a for loop to iterate through a group of values and copy the matching ones into its matching column. The problem we were trying to solve was: an extract from one of our systems had all the different types of researcher IDs grouped together in a column (e.g. Scopus_ID, WoS_ID, PubMed_ID etc). Some researchers had no IDs, others had all of them, others had redundant duplicates.

**Comment by ljsmart** [comment]
Finding, matching, and sorting is common use case I think. I'm currently dealing with an inherited tech report digitization project with really bad tracking data and documentation. I've got a list of 908 MARC records for the collection of reports and a directory full of pdf files. And the numbers don't match up.

**Comment by ljsmart** [comment]
Finding, matching, and sorting is common use case I think. I'm currently dealing with an inherited tech report digitization project with really bad tracking data and documentation. I've got a 908 delimited records for the collection of reports and a directory full of pdf files. And the numbers don't match up.  

The pdf file names are a variation of the call number which substitutes underscores for spaces.  So, the task is to go into the delimited file, convert the call numbers to the file naming convention then match up the resulting list with the list of pdfs then spit out the records with no pdf match. That way, I know which tech reports still need to be scanned.

**Comment by drjwbaker** [comment]
@ljsmart Thanks so much for this use case. Seems shellable to me. Do you mind sharing some examples of the call numbers and file names? (having real world patterns to work with is better than making them up!)

**Comment by ostephens** [comment]
@weaverbel an example of "Fetching files from list of URLs in a file":

Downloading data from KB+ (online service listing titles in e-journal packages):
- Given a list of package names and URLs from KB+ in a csv file like:

> A.P. Publications Limited:Master,publicExport/pkg/609?format=csv
> ABREES:Master,publicExport/pkg/1500?format=csv
> ACCA:Master,publicExport/pkg/610?format=csv

- iterate through the list
- add the domain/path to the URL
- download the files at those URLs

Shell command would look like:

`while IFS=, read f1 f2; do wget --no-check-certificate "http://www.kbplus.ac.uk/kbplus/"$f2; done < /path/to/file.csv`

Does that make sense?

**Comment by ljsmart** [comment]
I don't mind sharing at all. In fact, I'll offer up csv lists of the pdfs and collection call numbers as data for exercises. I'm currently on vacation and traveling over the U.S. long weekend, but will add the file to the github as soon as I'm able upon my return to the office.

**Comment by drjwbaker** [comment]
Awesome! Thanks @ljsmart

**Comment by antonangelo** [comment]
I'm thinking of an exercise combining grep and tail for reading logs: `tail -f | grep -i "ERROR"`  That includes command redirection as well.  the flow might be

-`cat`
-`grep`
-`tail`
-`pipe`

The challenge is not having a raw, being written to in real time, log file, and finding a file that has been anonymised.

**Comment by thomasgpadilla** [comment]
@drjwbaker and I put together a bunch of shell oriented examples that admittedly leverage other tools, e.g. ffmpeg and tesseract. Re: librarian use case, I use tesseract from time to time to generate plain text derivatives to support digital scholarship instruction, primarily in the humanities. 

https://datapraxis.github.io/sourcecaster/

**Comment by ljsmart** [comment]
@drjwbaker I'm assuming the csv files should be added to https://github.com/data-lessons/library-shell/data rather than here in the librarycarpentry general repo? Re: examples 

Call numbers look like this: 
Z699 .C3 no.4
Z699 .C3 no.00-43

File names for the associated pdf  look like this: 
Z699.C3_4.pdf
Z699.C3_00-43.pdf

**Comment by drjwbaker** [comment]
@ljsmart Yes please!

**Comment by thomasgpadilla** [comment]
Perhaps its out of scope but I do think it might make sense to create something that leverages tools w/ shell that dont exist natively as part of an OS - e.g. [various dependencies](https://github.com/datapraxis/sourcecaster). My sense of library work in this space is that it often naturally requires tools that are not standard to an OS. 

Further, this would require an introduction to installing various dependencies from the shell using package managers and otherwise. I've often found that one of the primary barriers for some tools that I work with comes at the point of installation, e.g. 

http://www.opener-project.eu/getting-started/how-to/local-installation.html

**Comment by ljsmart** [comment]
@drjwbaker It's done. I forked, added files, and submitted pull request. Hope I did that right. I made the files .txt rather than .csv. Because Excel was messing up the .csv, like it does.
