### ISSUE TITLE
Discuss how to manage more examples and use cases

### ISSUE THREAD

**Issue by ccronje** [data-lessons/librarycarpentry#32]
It would be good to have an easy way for the community to include more examples/use cases in each lesson without impacting on the lesson's core worked examples and length/time concerns. The discussion that sparked this issue: https://github.com/data-lessons/librarycarpentry/issues/31.

One solution might be creating a markdown file in each lesson where we can keep adding 'recipes', like this https://github.com/OpenRefine/OpenRefine/wiki/Recipes.

**Comment by drjwbaker** [comment]
The problem of using the wiki - as far as I can see - is that if learners are working from (say) http://data-lessons.github.io/library-shell/02-counting-mining/ and the instructor wants to use an alternative lesson at https://github.com/data-lessons/library-shell/wiki, is pushing learners to a new webpage unnecessary added confusion?

What about the 'options' model at http://data-lessons.github.io/library-shell/03-free-text/?
