### ISSUE TITLE
Can someone make me an 'organisation owner' of https://github.com/orgs/data-lessons/teams/library please

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/librarycarpentry#34]
I want to be able to assign issues to people but I need to add them to the team here to do that and I can't unless I'm an 'organisation owner'. @weaverbel?

**Comment by tracykteal** [comment]
Can you enable two-factor authentication on your account? Then I can add you as an organization owner.

**Comment by drjwbaker** [comment]
@tracykteal Done.

**Comment by tracykteal** [comment]
Great, you should be set!

**Comment by drjwbaker** [comment]
Thanks Tracy!
