### ISSUE TITLE
SQL lectures

### ISSUE THREAD

**Issue by jcolomb** [data-lessons/librarycarpentry#36]
Let's see what exists as sql courses.

----

you may check sololearn course on SQL, I got my basics there.
@rissom talked about https://sqlzoo.net

(#mozsprint, please label it dear admin)

**Comment by jduckles** [comment]
The Carpentries have extensively taught SQL lessons:
* http://swcarpentry.github.io/sql-novice-survey/
* http://www.datacarpentry.org/sql-ecology-lesson/

The ecology lesson from Data Carpentry is probably more along the lines of the level at which would resonate with LC. I suggest you use the structure of an existing lesson and adapt it to a data set more interesting to librarians.

**Comment by drjwbaker** [comment]
Closing. Reopen if you think appropriate.
