### ISSUE TITLE
Review/Revise Git lesson

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/librarycarpentry#37]
@ndalyrose and @alexandermendes are going to work through, revise, and improve the Git lesson tomorrow (British Library, UK site). Refer to https://github.com/data-lessons/library-git/issues/7 during the work.

**Comment by drjwbaker** [comment]
@ndalyrose and @alexandermendes: when you get a minute, could you please report back here on what was achieved and - if appropriate - close this issue. Ta!

**Comment by alexandermendes** [comment]
Sure, I made some changes to lesson 2 on Friday but of course this has the knock on effect of requiring some updates to the following lessons. I'll do something quickly now so that we can close this.

**Comment by weaverbel** [comment]
All the pull requests have been handled @alexandermendes -nothing is outstanding at this point.

**Comment by alexandermendes** [comment]
Ah yeah, I just had one locally that I didn't submit, will do soon.

**Comment by alexandermendes** [comment]
So let's close this after https://github.com/data-lessons/library-git/pull/43 is merged. So we have basically tidied up the setup and lessons 1-3. I would suggest that lesson 4 could become a brief intro to forking/branching, as there is nothing on this yet, and the GitHub Pages lesson needs work, but will have to leave this here for the time being.
