### ISSUE TITLE
pin this repository 

### ISSUE THREAD

**Issue by evanwill** [data-lessons/librarycarpentry#41]
It would be helpful to pin this repository for the org so it is easy to find and use as a "metarepository" for on going discussion and development documents (i.e. like [SWC org page](https://github.com/swcarpentry)).

**Comment by drjwbaker** [comment]
Good idea @evanwill. Didn't know that was possible. Though we share this repo with some DC stuff, so not sure if we can. @tracykteal?

**Comment by evanwill** [comment]
If someone who has admin for the organization goes to the org page, https://github.com/data-lessons , they will see a little link saying "Customize pinned repositories" next to the green "New" button. Click it to select up to 6 repositories to be pinned

**Comment by jduckles** [comment]
I made a meta-repository for SWC that helps guid people on first GitHub contact with the organization page. Perhaps something similar for data-lessons is in order. 

You can see it at the top, pinned here: https://github.com/swcarpentry

When you click on it you see a README.md https://github.com/swcarpentry/swcarpentry

**Comment by weaverbel** [comment]
I have admin rights but no clue how to do what @jduckles suggests. Happy to do it on behalf of the group if someone gives me some steps.

**Comment by jduckles** [comment]
Details on how to pin a repo are here: https://github.com/blog/2191-pin-repositories-to-your-github-profile

**Comment by weaverbel** [comment]
Hi @jduckles Thanks - I do know how to pin as I have done that for my own repos - but did you do anything special for the Software Carpentry thing with the README? 

Also, if we were to pin just one (we can have up to 5, so not 8), it should probably be the librarycarpentry repo we used for the sprint? Or the one we serve the blog from? What do others think? @drjwbaker @ostephens

**Comment by drjwbaker** [comment]
I'd pin https://github.com/data-lessons/librarycarpentry as we will unSprint it soon and return it to just the master/meta LC repo. The website one needs to be refreshed, moved, binned at some stage, so I wouldn't want to hang our hat on that.
