### ISSUE TITLE
centralized setup?

### ISSUE THREAD

**Issue by evanwill** [data-lessons/librarycarpentry#42]
In each individual lesson I have noticed issues with the setup instructions. It seems unclear if each lesson should explain the complete set up process, or just the specific tool being introduced. For example, should the Git lesson explain how to install Git, set up the terminal, and get a decent text editor, or will participants have that already? 

SWC has a centralized initial set up as part of the main [workshop page](http://swcarpentry.github.io/workshop-template/), then each lesson has a very basic [set up page](http://swcarpentry.github.io/git-novice/setup/) since everything is already installed. 

The biggest barrier is making sure Windows machines are set up correctly to use the terminal. In the past this relied on Git Bash (part of Git-for-Windows), plus a SWC [windows-installer](https://github.com/swcarpentry/windows-installer/) that added Nano editor, Make, and SQLite to Git Bash. However, the installer is out-of-date and Nano no longer works on current versions of Git Bash. Thus we need some workaround if a lesson assumes the use of Nano.

So I guess my question will there be a central Lib Carpentry setup where we say get a text editor, get a terminal set up, etc? Or do we have to add all the necessities to each lesson so they can stand more independently?

**Comment by drjwbaker** [comment]
Thanks @evanwill. You are right. This has been further complicated by template changes that has come down from SWC: notably setup.md.

For me is should be technical setup. Data download, installation, and validating install etc cetera.
Our workshop webpage template - eg https://datascienceinlibraries.github.io/2017-05-18-pitt/ - is good on that. The lesson pages less so.

As every LC workshop is different and teaches different stuff, the best approach - IMO - is to raise an issue on each lesson repo pointing to the style we want and then monitoring progress here.

There are lots of consistency edits needed post sprint. We need a person on each to share the load. Are you willing and able to take this one?
