### ISSUE TITLE
UnSprint this repo

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/librarycarpentry#43]
We need to revert this repo back to our meta LC repo for lesson development et al. Thought on timescales and tasks? I'm feeling we need to align with https://github.com/data-lessons/librarycarpentry/issues/22 as the readme here should list lessons, their status, et cetera.

**Comment by weaverbel** [comment]
I can unsprint the repo and add links to lessons and then others can make other changes @drjwbaker .

**Comment by tracykteal** [comment]
Is this sung to the tune of 'unbreak my heart'?

**Comment by weaverbel** [comment]
I have done two 'unsprints' for the files - what else needs doing on them @drjwbaker ?

**Comment by drjwbaker** [comment]
Looks it.

I've raised a PR for the readme with the incubator status more fleshed out https://github.com/data-lessons/librarycarpentry/pull/46

Input very welcome.
