### ISSUE TITLE
Website redesign

### ISSUE THREAD

**Issue by weaverbel** [data-lessons/librarycarpentry#49]
The amazing @richyvk has done a fabulous job with the website redesign http://www.richyvk.me/library-carpentry-redesign/ so let's start to move on this. Issues should be raised here.

Repo view is here: https://github.com/richyvk/library-carpentry-redesign if people want to fork and do some pull requests.

I think it is pretty nice. We do have to think about reskinning the blog to match though.

**Comment by drjwbaker** [comment]
I love it! Thanks @richyvk. I have some comments but let's save for a catchup call.

On which, I'm teaching LC in Padua next week, so perhaps we can schedule the chat between when I'm back (20 September) and the end of the month. I've opened a issue for just the call here https://github.com/data-lessons/librarycarpentry/issues/50

**Comment by chodacki** [comment]
It is awesome, @richyvk   Thanks for all the legwork!

**Comment by weaverbel** [comment]
I am working on the website for the sprint.
