### ISSUE TITLE
LC September 2017 Community Call

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/librarycarpentry#50]
Forking from https://github.com/data-lessons/librarycarpentry/issues/48 we need a catchup.

**Possible Agenda**
- saying hi and stuff
- @richyvk's awesome website work https://github.com/data-lessons/librarycarpentry/issues/49
- update from @chodacki on LC related bid success
- pre-chat about our place in the SWC/LC merger https://github.com/data-lessons/librarycarpentry/issues/48#issuecomment-327015590
- tentative hands up to be on steering committee for us to become a 'Lesson Organisation' under The Carpentries umbrella (to be in place by January)

**Date**
I propose sometime between 20 September and 29 September.

**People**
From: @weaverbel @richyvk @tracykteal @gvwilson @ndalyrose @jt14den @chodacki @tracykteal @mkuzak @pitviper6

**Comment by chodacki** [comment]
Sounds good.  However, I am unavailable Sept 17-29 (part of this is presenting on LC at RDA in Montreal).  I could do Oct 2-13 or Oct 30-Nov 3 though.  Does that work?  Wanna doodle?

**Comment by mkuzak** [comment]
Great. I should be available. I will need to check once there is a more detailed date.

**Comment by tracykteal** [comment]
OK, I created a 'whenisgood' poll for Oct 2-13th.

Time zones are going to be a challenge, so I put in a lot of times. It might be that there will need to be 2 meetings to include all the people who want to participate. 

Fill out the poll here:
http://whenisgood.net/8pnn359

Results will appear at http://whenisgood.net/8pnn359/results/4e4wbae so anyone can check to see what times look promising.

I also created an etherpad for the call: http://pad.software-carpentry.org/lc-call

**Comment by drjwbaker** [comment]
Thanks @tracykteal For some reason I always forget the name whenisgood when I'm thinking of setting up a meeting (which is frustrating as it is so much better than doodle poll!)

**Comment by cmacdonell** [comment]
Wow, those whenisgood results are not what I'd hoped for. Lots of conflicts. Anyway, do we want to pick a time?

**Comment by gvwilson** [comment]
I'll stay up/wake up whenever is convenient for others.

**Comment by drjwbaker** [comment]
@cmacdonell Thanks for taking this on. Perhaps pick two, one at either end of the timezone equation?

**Comment by weaverbel** [comment]
And I can be up early / stay late #usedtoit

Belinda Weaver
Community Development Lead
Software and Data Carpentry
e: bweaver@carpentries.org | p: +61 408 841 882 | t: @cloudaus

**Comment by cmacdonell** [comment]
Tuesday, October 10 at 7am US/Pacific has only 3 exclusions. @weaverbel @pitviper6 @richyvk can work some magic to join the rest of us at that time despite saying that time didn't work?

**Comment by pitviper6** [comment]
I'm at an all day meeting, so the 9th and 10th are completely out for me,
alas.

**Comment by richyvk** [comment]
@cmacdonell That would be midnight Brisbane time, unless I'm wrong. I love LC but I don't think I'd be any use to anyone at that time :(

**Comment by weaverbel** [comment]
Midnight here so not ideal but I could sacrifice myself for Library
Carpentry ;-)

Belinda Weaver
Community Development Lead
Software and Data Carpentry
e: bweaver@carpentries.org | p: +61 408 841 882 | t: @cloudaus

**Comment by chodacki** [comment]
I can do 7am Pacific.

**Comment by tracykteal** [comment]
We could do two times like with SWC/DC Community Calls. There's one at 2pm UTC and another at 11pm UTC http://everytimezone.com/ Then people could make one time or the other. Agenda is the same for each call, so we take notes and can read the notes to catch up on what was discussed on the other call. Unfortunately, there doesn't really seem to be one good global time.

**Comment by mkuzak** [comment]
I should be able to join 2pm UTC.

**Comment by drjwbaker** [comment]
Can we do what @tracykteal suggests please. It is a more articulate version of what I was trying to get at here https://github.com/data-lessons/librarycarpentry/issues/50#issuecomment-330502251 :)

**Comment by cmacdonell** [comment]
Ok, if we add 2pm US/Pacific, on Wednesday, Oct 11 as our second meeting, that will catch @pitviper6 @weaverbel @richyvk. @chodacki happens to be available for either.

It's not the same day, but due to @pitviper6 's all-day meetings on the 9th/10th, I think this is better.

**Comment by pitviper6** [comment]
I would very much appreciate that option! Thank you.

Juliane.

**Comment by drjwbaker** [comment]
@cmacdonell Thanks for wrangling. Can you confirm the UTC times of the 10 and 11 October meetings please?

**Comment by cmacdonell** [comment]
Here are our meetings, shall I email them to the Discuss list?

Tuesday, Oct 10, 14:00/2pm UTC
Wednesday, Oct 11, 21:00/9pm UTC

**Comment by tracykteal** [comment]
Sure! I've already set up the etherpad, so information can go there.

http://pad.software-carpentry.org/lc-call

I put the day and times on the etherpad, and these are the timeandday links, so people can figure out what times things are in their local time zones (there are some time changes coming up!). I added Zoom connection details too. 

First call:
October 10, 2017 14:00/2pm UTC
Click here for your local time: https://www.timeanddate.com/worldclock/fixedtime.html?msg=Library+Carpentry+call&iso=20171010T14&ah=1

Second call:
Oct 11, 21:00/9pm UTC
Click here for your local time: https://www.timeanddate.com/worldclock/fixedtime.html?msg=Library+Carpentry+call+2&iso=20171011T21&p1=%3A&ah=1

If you are planning to post it on Discuss and have new people on the call, it would be good to plan an update on LC at the beginning of the call too.

**Comment by drjwbaker** [comment]
Are we adding names on the pad to the call we are coming to? Either way, I have. Speak soon folks.

**Comment by weaverbel** [comment]
Hi @cmacdonell I think we should tell people via @LibCarpentry twitter and also by the gitter rooms and also tell people in our networks, but I think these calls should really be for the community as it is now - people who have taught or sprinted or contributed somehow - to have a say and maybe we could schedule other calls later for the wider community of Carpentry folks to chime in.  We don't really want to spend time getting newbies up to speed on what LC is and yada yada - we want these calls to be a focused hour where we plan the next steps based on the knowledge we share of where we are now. 

I am thinking of creating a Google form where people can nominate a person or persons (or even themselves) to serve on whatever governance structure, e.g. steering committee, emerges from the calls. 

Maybe add a thumbs up / down or your owncomment on that idea?

Also I am thinking of writing a **State of Play in LC** to sum up where we are at. It could reference the posts I did post-2016 and -2017 sprints and also mention the Australian roadshow, the trip @jt14den is about to do in South Africa, info about @chodacki 's IMLS grant and what that means, and other news that people should ideally be on top of before we dive into these calls. Good plan? I could make it a blog post on librarycarpentry.github.io and people could contribute or review before it is posted. Thoughts @tracykteal @drjwbaker @jezcope @ostephens @ccronje @pitviper6 ????

**Comment by cmacdonell** [comment]
After thinking about it, I agree that this call should be for those who are already participating.

I think the suggestion about a blog post is a good one as well.

I would say it's likely that a small steering committee is the right governance model (but we can discuss in the call), then we can nominate people & vote in some way after.

**Comment by chodacki** [comment]
Good plan. We have tweeted this out from libcarp handle. Others should do the same from their accounts. I will do more promotion to my networks next week.

**Comment by mkuzak** [comment]
+1 one for meeting fo already involved
+1 for the post
mentioned by @weaverbel above

**Comment by pitviper6** [comment]
I think we should definitely treat this call as something that people need to come prepared for - there is a lot to go over, so people should be familiar with LC and what it's been doing.  However, if some newbie joins the call, so be it. They'll get a crash course in LC.

I'm getting slightly conflicting views from @weaverbel and @chodacki about how generally we want to publicize this. I was going to go ahead and tweet the etherpad link, and perhaps add a notice/etherpad link to the front page of our current website. Yes or no on that second thing?

**Comment by cmacdonell** [comment]
I read both their comments as tweeting notices is OK, but we'll avoid the Discuss list for now, or saying anything like "Come checkout LC" that would attract new people. I certainly agree we won't chase anyone away, but this is a community call that should have focus to it. 

We'll make sure to get a clear agenda on the etherpad in advance of the meeting. I'll take that on.

**Comment by weaverbel** [comment]
Thanks Cam - it is fine to tweet, blog and publicise this in our library
community forums - I just didn't want it on the discuss list or other
places where we might get people coming in for the first time wondering who
the hell we are ;-)

I am hoping to write a "how we got here" blog post on the plane to Perth -
am at the airport now.


Belinda Weaver
Community Development Lead
Software and Data Carpentry
e: bweaver@carpentries.org | p: +61 408 841 882 | t: @cloudaus

**Comment by cmacdonell** [comment]
Hi everyone,

Look forward to seeing those who can make it tomorrow, the Zoom contact and basic agenda are on the etherpad.

http://pad.software-carpentry.org/lc-call

See you at 14:00/2pm UTC Tuesday

The second call is Wednesday, Oct 11, 21:00/9pm UTC. That info is also in the etherpad.
