### ISSUE TITLE
Update README links to non-deprecated projects

### ISSUE THREAD

**Issue by jcoliver** [data-lessons/librarycarpentry#51]
The links in the [README](https://github.com/data-lessons/librarycarpentry/README.md) link to old (deprecated) locations and should probably be updated to the repos of active development. e.g. replace 

[https://github.com/data-lessons/library-data-intro-DEPRECATED](https://github.com/data-lessons/library-data-intro-DEPRECATED) 

with 

[https://github.com/LibraryCarpentry/lc-data-intro](https://github.com/LibraryCarpentry/lc-data-intro)

**Comment by weaverbel** [comment]
Fixed - thanks @jcoliver
