### ISSUE TITLE
Digital Preservation lesson

### ISSUE THREAD

**Issue by peterneish** [data-lessons/librarycarpentry#52]
At a recent Australasia preserves workshop ([blog post](https://blogs.unimelb.edu.au/digital-preservation-project/2018/03/06/australasia-preserves-establishing-a-digital-preservation-community-of-practice/), [meeting notes](http://bit.ly/2ogSt1U)), the idea was floated for some kind of digital preservation carpentry lesson or teaching material. It is not much more than an idea at this stage, but I would like to see a discussion on whether this is feasible and where it would fit? Would it make sense to be part of the archive carpentry lesson, or is it more stand alone?

Topics that could be covered in a lesson would include a general introduction as well as hands-on activities with open source tools creating checksums and fixity checking, file format identification, working with disk images etc.

**Comment by libcce** [comment]
This recent IMLS report, Open Digital Preservation Training and Professional Development Opportunities, might be useful to this discussion:
https://www.imls.gov/sites/default/files/publications/documents/imls-2017-open-project-report.pdf
It provides possible themes and resources to draw from. For instance, I'd like to see lesson material developed around web archiving and maybe @ianmilligan1 is interested?

**Comment by peterneish** [comment]
Thanks Chris, that looks report looks great. 

Would appreciate advice on what has worked for scoping and developing lessons.  Do we: develop use cases, conduct survey of community, dive in and develop a minimum viable product (then iterate), all of the above?

**Comment by libcce** [comment]
Library Carpentry Mozsprint is a great place to ask these questions and gauge interest (and Belinda has labeled your issue). There is also some information on the lesson incubation process https://software-carpentry.org/lessons/incubation/.

**Comment by peterneish** [comment]
New repository created thanks @weaverbel https://github.com/LibraryCarpentry/lc-dig-pres - discussion can continue at that repo.
