### ISSUE TITLE
Library Carpentry: managing future development

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/librarycarpentry#6]
# Library Carpentry - state of play October 2016

This document is an attempt to define/agree what we consider to the be the core principles of Library Carpentry. It is written in the context of the (very exciting) expansion in recent months of Library Carpentry in terms of what it is offering, where it is being offered, and who is being offered.

---
## What is Library Carpentry?

Library Carpentry is software skills training aimed at the needs and requirements of library professionals. Training takes places in face-to-face workshops where one or more of the developed modules are taught. Modules are also made available online (CC BY, published via GitHub Pages) for self-directed study or for adaption and reuse by library professionals.

Library Carpentry is in the commons and for the commons. It is not tied to any institution or person.

---
## What is a workshop

A Library Carpentry workshop comprises one or more half-day, face-to-face sessions where one or more of the currently developed modules are taught. Ideally, 4 modules (e.g, Data Intro, Shell, Git, OpenRefine) will be taught in a workshop across four half-day sessions, but this is not mandatory. Organisers may prefer to teach the workshop over two or more days. While the original material is key, organisers may choose to swap in the SQL module to replace one of the core lessons, or teach it in addition. Workshops are interactive. Ideally attendees will bring their own laptop to workshop so that skills learnt can be replicated outside of the workshop without the need for additional setup.

Workshops are run by a team. Ideally this will consist of:
- a [Host](http://software-carpentry.org/checklists/host/) (who is the principal local contact for the workshop)
- [Instructors](http://software-carpentry.org/checklists/instructor/) (who present the tutorials and lead the practical exercises)
- a [Lead Instructor](http://software-carpentry.org/checklists/lead/) (who is in charge of deciding what will be taught by whom and ensuring the teaching aspects of the workshop go smoothly)
- [Helpers](http://software-carpentry.org/checklists/helper/) (who provide assistance during practical sessions). Workshops can be any size. 

To maintain the quality of Library Carpentry workshops, it is highly recommend that a Software/Data Carpentry certified instructor is present at each workshop. For more on Software/Date Carpentry instructors and instructor training, see http://software-carpentry.org/join/. 

---
## What is a module

A Library Carpentry module is a set of training materials that can be used either to run a half-day, face-to-face training session or as self-directed learning. Each module comprises 3-4 sections, is interactive, works across Windows, OS X, and Linux operating systems (with all setup instructions included) and has a combination of follow-my-leader sections and exercises (and additional exercises) that map to library practice. Modules introduce software and concepts relevant to librarians and have a preference for open source and widely used software. Data used in exercises is library-related, e.g. bibliographic data.

---
## Who is an instructor

A Library Carpentry instructor is anyone willing to lead a Library Carpentry workshop. There are at present no prerequisites or training required to run a workshop. Going forward we will continue to evaluate this, mindful of the success of the Software Carpentry [Instructor Training](http://swcarpentry.github.io/instructor-training/) approach and with the ambition for the lead instructor of every Library Carpentry workshop to have undergone Software Carpentry [Instructor Training](http://swcarpentry.github.io/instructor-training/)

---
## How Library Carpentry is managed

Library Carpentry was developed and is maintained by volunteers. There is no central organisation or command structure, and all activity is - at present - voluntary.  Management and maintenance are distributed. Each module is 'owned' by one of more individuals responsible for coordinating maintenance of that module. Changes to lessons are managed using the GitHub Issue tracker. Announcements and initial discussion take place on [Gitter](https://gitter.im/weaverbel/LibraryCarpentry). New members are welcome to join this community.

**Comment by drjwbaker** [comment]
I should add that I am not wedded to this in terms of content, format et cetera. So please freely discuss, suggest edits, et cetera. My online caveat is the briefer the better!
The intention is for this to end up online (ideally alongside every lesson) and to be reviewed from time to time. We should also run it by library friends for comment once we are happy. I also hope this document will become the basis for how we describe LC to people.

**Comment by weaverbel** [comment]
Looking good @drjwbaker - just amending typos - will do para by para

This document is an attempt to define/agree what we consider to be the core principles of Library Carpentry. It is written in the context of the (very exciting) expansion in recent months of Library Carpentry in terms of what it is offering, where it is being offered, and to whom it is being offered.

**Comment by weaverbel** [comment]
Suggested changes to

## What is a workshop

A Library Carpentry workshop comprises one or more half-day, face-to-face sessions where one or more of the currently developed modules are taught. Ideally, 4 modules (e.g, Data Intro, Shell, Git, OpenRefine) will be taught in a workshop across four half-day sessions, but this is not mandatory. Organisers may prefer to teach the workshop over two days. While the original material is key, organisers may choose to swap in the SQL module to replace one of the core lessons, or teach it in addition. Workshops are led by trainers and supported by helpers. Workshops can be any size. Workshops are interactive. Ideally attendees will bring their own laptop to workshop so that skills learnt can be replicated outside of the workshop without the need for additional setup.

**Comment by weaverbel** [comment]
suggested changes to

## What is a module

A Library Carpentry module is a set of training materials that can be used either to run a half-day, face-to-face training session or as self-directed learning. Each module comprises 3-4 sections, is interactive, works across Windows, OS X, and Linux operating systems (with all setup instructions included) and has a combination of follow-my-leader sections and exercises (and additional exercises) that map to library practice. Modules introduce software and concepts relevant to librarians and have a preference for open source and widely used software. Data used in  exercises is library-related, e.g. bibliographic data.

**Comment by weaverbel** [comment]
suggested changes to

## How Library Carpentry is managed

Library Carpentry was developed and is maintained by volunteers. There is no central organisation or command structure, and all activity is voluntary.  Management and maintenance are distributed.. Each module is 'owned' by one of more individuals responsible for coordinating maintenance of that module. Changes to lessons are managed using the GitHub Issue tracker. Announcements and initial discussion take place on [Gitter](https://gitter.im/weaverbel/LibraryCarpentry). New members are welcome to join this community.

**Comment by jezcope** [comment]
Thanks @drjwbaker, this looks really good. @weaverbel I particularly agree with "Organisers may prefer to teach the workshop over two days." — this has come up in conversation with colleagues for whom larger geographic distances between institutions would make an overnight stay preferable. The weekly format works well for somewhere population-dense like London, but maybe not so much for the north of England.

**Comment by pitviper6** [comment]
@drjwbaker @weaverbel @jezcope  I agree with the ""Organisers may prefer to teach the workshop over two days." but should we change it to "two or more" - some may want to make more than two days, especially if adding on the SQL or persistent identifier lessons.  Here in congested Southern California, there are often week long workshops because people can take the train to a campus and then get cheap accomodations.

**Comment by pitviper6** [comment]
And thanks for putting this together, James! Our workshop has been so successful that I've had interest from departments in the library on getting involved, and how much time/effort was required by LC to instruct, etc. It'll be great to have something consistent to point them to, to get an idea of what LC is and entails.

**Comment by tracykteal** [comment]
Thanks, this is all great, and important to put together! You have created a great curriculum here. 

Software Carpentry has been coordinating Library focused Software Carpentry events, that I think have even been called Library Carpentry. Do you want this to continue? If SWC or DC are coordinating, then they would need to have at least one SWC/DC qualified instructor, so if you do want to continue that and want them to use this material, we might need to add that caveat here or somewhere else. 

Should we start a thread about if and what support and relationship you want from SWC/DC in terms of instructors, templating and such? 

cc @jduckles

**Comment by Repositorian** [comment]
Piping in from the land of #AuthorCarpentry - an initiative at CaltechLibrary for training scientists/researchers in best practices around writing, publishing, scholarly identify and reputation. We are also working through the best way to co-exist with DC, DW and now LC!  At this point we have piloted a few lessons at the CODATA-RDA Summer School in Research Data Science and it looks like the program will be more formally incorporated going forward through this venue.  Also ANDS has been in touch about their plans to try out the AC lessons at Open Access Week Australia. 

We would be pleased to discuss further what it means to be a spin-off Carpentry in a way that leverages the highly successful models of DC and SC without imposing/confusing the brand.  All guidance and suggestions arising out of this discussion will be most helpful.

**Comment by ccronje** [comment]
Thanks this is excellent. Could we add the [log sheet](https://docs.google.com/spreadsheets/d/17EMzgODvvX4qnfpNvHkdIi3VzZp3r_sdYHld1YrpB-A/edit#gid=0) to **What is a workshop**? It will help illustrate the definition and is valuable in other ways e.g. lessons learned. Could we ask that people add to it?

**Comment by drjwbaker** [comment]
Right. Two things going on here.
1) I will update the blurb based on your wonderful suggestions
2) We need to think through SC/DC relationship in a separate place (which will then feed back into this). I'll set up a fresh issue.

**Comment by drjwbaker** [comment]
Update: blurb above revised.

Where shall we put it?

**Comment by pitviper6** [comment]
That was a great call! It was nice to see everybody in one room, so to speak (with a cat!).  To follow up, as I stated before, I'm working for UCSD at 70%, so I do have the elusive librarian free time to work on some things to help along Library Carpentry development.  Here's a few things I could do in the next few months, as a sort of bridge between now and when more concrete things might start happening:  

1. I would be willing to be the point person for LC workshop requests that Tracy receives.  I've organized and taught an LC workshop, so I know what is involved in that effort, and I do know some SWC-certified instructors who could teach the four basic lessons (data fundamentals, shell/bash, git, OR)
2. I'm very much interested in curriculum dev, having participated in the LC sprint and am currently working on the OR lessons (got a pull request up for comments, btw, go look at it!). I'd be happy to try and develop some loosely organized discussions about development, especially vis-a-vis the discipline-oriented lessons already found in Data Carpentry (do we want to Go There?)
3. Also, I'd be happy to do some research on funding.  As I said, I was a colleague at Harvard with Chris Erdmann, and was in the first cohort for the DST4L training, so I could pick his brain about potential funders, or how much interest there might be in some kind of lesson sharing.

Also, just a thought.  Librarians tend to be quite conference-oriented - they pick ALA or SLA or DLF or ACRL and find a professional home.  Contacting those organizations and seeing if they want an LC pre-conference workshop would probably be very fruitful, both in getting the LC movement out there, and for building the community. Librarians are starving for the skills LC teaches, and going to them at their major conferences could be a big step forward (once we get the instructor pool and develop enough to handle those kind of requests).

**Comment by chodacki** [comment]
@pitviper6 Thank you for volunteering to dedicate time to this effort.  I think its exactly the type of coordination needed right now.  And I really like Tracy's last point about focusing on the curriculum.  So, I agree your second point is key.  As for funding opportunities, I can help with your research.  And I like your point about conferences.  Another one would be IDCC in Edinburgh next spring.

**Comment by Repositorian** [comment]
The more transparent this activity can be, the more trust and buyin it will likely garner.

To that end, it might be helpful to clarify the roles and responsibilities for any point person who is handling the LC training requests referred by Tracy. Are they themselves doing the training, or determining who do the training, or are they putting out a call for potential trainers who are interested and available to teach that particular workshop? Can librarians at other institutions outside CDL allowed to be trainers? Are the rest of us who might receive training requests free to handle them ourselves, or is the expectation that we funnel all library-based requests to the Coordinator? Are the trainers being paid to lead or assist with such workshops? 

There arelibrarians and developers in our team who already teach command line, open refine, etc for librarians thru various non- Carpentry venues and they may be interested in teaching through Library Carpentry. This group has the opportunity to invite engagement from qualified colleagues who already teach this stuff but don't necessarily drink the same koolaid!

**Comment by drjwbaker** [comment]
@pitviper6 Thank you so much!

On 2), that would be awesome if you could offer oversight on how all the 5 modules are developing. On 'discipline-orientated lessons' I am not in favour, but what I am in favour of to tailor LC to the many and varied roles of librarians is to bulk out our additional exercises with more variety that touch on IRL concerns.

On 3), please do.

On conferences (and @chodacki) [CILIP](http://cilip.org.uk/) invited me to speak at a conference this summer, so making inroads there. And [LIBER](http://libereurope.eu/) are in my sights (I've been invited to speak at their annual before, but pre-LC).

**Comment by drjwbaker** [comment]
@Repositorian I've put a light-straw man workflow at https://github.com/data-lessons/librarycarpentry/issues/10. Feel free to burn it down :)

**Comment by pitviper6** [comment]
My thought was to put together a list of SWC/DC trainers internationally who are willing/able to do LC workshops. I'm not even sure anyone at CDL is currently certified!  

Transparency is key - I would expect to document all decisions/rationales/etc. here, as the community hub.

**Comment by chodacki** [comment]
@Repositorian I completely agree that we need to be transparent as we move forward.  I think a founding principle MUST be that we are for/by the commons...and not for a single institution.  

To respond to your comments about CDL's possible influence: Real quick, I am not interested in limiting this effort and CDL has ZERO ambition to own LC globally, nationally, or even California-wide. Basically, to clarify our role, I was suggesting we could offer a possible way for LC project coordination to be funded.  It would still require all communication and decision making remain within the commons.  Won't work without governance by this larger community.  

But just to restate...I understand your point...100%.  We MUST remain transparent as we move forward. We cannot survive/thrive any other way.  



(sidenote: We are building an effort alongside and reliant on two existing organizations: DC/SWC. So, I also see transparency as a way to ensure we are open with ourselves and them about our governance.  Its the only way we cane honest about how we are/aren't being influenced by their efforts, too.)

**Comment by Repositorian** [comment]
Thanks @chodacki for this... it is certainly a shared value to remain inclusive, transparent, and accountable and look forward to working with you all making Li rary Carpentry programming available as widely as painlessly as possible! :-)

**Comment by drjwbaker** [comment]
@chodacki Thanks for clarifying and, of course, for the capacity offer. 

While we are on transparency vis-a-vis our jobs, for my part it helps if I show momentum towards funding in which I am involved and in turn my employer receives funds (research funding in the UK is based around the model of funders buying out some of your time and/or all of the time for hires you bring in; so money to spend on stuff is good, but they like contributions to your wages/time). That said, at the moment their excited about the super secret prestige award LC is getting...

**Comment by jezcope** [comment]
Thanks everyone, I'm sad I had to drop out for my next meeting. On the time front, I don't have a lot of it at the moment, but I've got enough buy-in from my colleagues to get "Run a Library Carpentry workshop" as an official objective this year so I'll be able to provide some time on that basis at least.

I'll be speaking to Aleks Nenadic from [SSI](http://software.ac.uk/) next week so I can see if they are able to provide any support alongside the SWC/DC co-ordination for the UK they already do.

On conferences: I'll be attending [IDCC](http://www.dcc.ac.uk/events/idcc17) (as mentioned by @chodacki) in the spring and may be able to submit a practice paper on LC. It would certainly fit into the "Capacity development for open science skills and readiness" theme of the conference. Abstract deadline is Monday 17 October.

I gave a talk on sustainable software and its relevance to libraries at LIBER a couple of years ago and there was a lot of interest.

**Comment by jezcope** [comment]
I've also started reorganising the library website (see [this branch on my fork of erambler.github.io](https://github.com/jezcope/librarycarpentry.github.io/tree/feature/restructure-site)) and cleared a space on the home page for the information above — does that seem a good place to put it once finalised?

**Comment by drjwbaker** [comment]
@jezcope On the website, see query at https://github.com/data-lessons/library-data-intro/issues/21 from someone who found us.

On IDCC fab and LIBER is on my target list.

On SSI, are you speaking to Aleks in person or on a call? I've belatedly twigged that are some potential follow-on possibilities from my fellowship..

And great on the objective! Perhaps we can target some new exercises to the needs/requirements of the cohort?

**Comment by cmacdonell** [comment]
Hi, just one clarification of language that may avoid future confusion.

In the SWC/DC vernacular, **instructors** teach workshops and **trainers** are something different.  **Trainers** train instructors.  Trainers are likely instructors themselves too, but the role of trainer within SWC/DC is to train those want to teach workshops.

So when @tracykteal spoke of training, she is referring to sessions where trainers (such as herself, Greg Wilson and few others) teach those who want to be instructors.

So with regards to running workshops, we should be talking about having certified SWC/DC instructors, not SWC/DC trainers.

**Comment by drjwbaker** [comment]
Huh, I had never noticed that linguistic quirk before! I shall fix various bits of text tomorrow.

**Comment by tracykteal** [comment]
Thanks @cmacdonell. Important clarification.

**Comment by chodacki** [comment]
Following up on number 2 above ( @drjwbaker @pitviper6 ) I know this can be virtual or in person...but If we want to set up in-person curriculum development workshops where we get LC folks together and work on new modules and QA/finalize each others, maybe we plan on regional events. We could organize workshops at IDCC in Scotland, at Open Repositories in Brisbane, and another at a North American library event.  If that sounds like a good idea, we can coordinate which modules we want to tackle and start talking to the conference organizers about the logistics.

**Comment by weaverbel** [comment]
@pitviper6 I am a certified SWC/DC instructor and am happy to teach LC - I think I might have proved that already ... ;-)

**Comment by pitviper6** [comment]
@chodacki John, I think that's a great idea! SLA just put out a call for workshops for their 2017 conference in Phoenix the second week of June - just as an example a North American library conference. The challenge here is coordinating lessons and efforts so that we incorporate all the great ideas without duplicating effort. I know this is going to sound administrative-ish, but perhaps thinking about who/what to target and when is a good starting point?

**Comment by weaverbel** [comment]
Definitely +1 to library conferences. I just presented a brief Library Carpentry workshop to the Australian Library & Information Association Conference and got about 70 people - maybe could have got more but there were competing talks and events. LOTS of interest and follow ups and many a positive tweet. Definitely a great forum and the young librarians are really keen to get these skills.

**Comment by tracykteal** [comment]
Thanks @jezcope for those updates to the website. I think outlining 'what does Library Carpentry teach' is an important part of this 'state of play' document. 

We have that overview for our [Ecology workshop](https://github.com/datacarpentry/ecology-workshop) and [Genomics workshop](http://www.datacarpentry.org/genomics-workshop/) (admittedly not with great formatting), and I think the one you have listed on http://librarycarpentry.github.io/ is really useful for understanding what Library Carpentry teaches.

**Comment by jezcope** [comment]
Thanks @tracykteal, but I can't claim credit for anything other than fixing the logos at the bottom of the blog page. @jcoliver did the hard work! :grinning:

**Comment by jcoliver** [comment]
Glad to help out, @jezcope , even if it was largely selfish (I'm presenting to a group of librarians, and I wanted a one-stop spot with all the lessons).

**Comment by drjwbaker** [comment]
@jcoliver Well that sounds like a good selfish reason to me! If any interest in running a workshop comes out of this, do let us know via http://librarycarpentry.github.io/about/
