### ISSUE TITLE
Add Contributor and Maintainer information to lessons

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/librarycarpentry#8]
At present, who names of Maintainers and Contributors are not listed with the lesson. I propose we put the former on the lesson front pages (eg http://data-lessons.github.io/library-data-intro/) and the latter on the lesson readmes (eg https://github.com/data-lessons/library-data-intro/blob/gh-pages/README.md)

I'm happy to take on this work. Do we have quora?

cc @mkuzak

**Comment by mkuzak** [comment]
+1

**Comment by ostephens** [comment]
I think the pattern on SWC courses is to have Maintainers in the README and Contributors in AUTHORS?

I'm not sure we need maintainers on the lesson front pages?

**Comment by mkuzak** [comment]
I don't have much preference, but it may be better to adhere to SC guidelines for consistency.

**Comment by drjwbaker** [comment]
Okay, I was just thinking about people getting appropriate credit for their efforts. I'll take is as an action to update following SC guidelines.

**Comment by jezcope** [comment]
+1 to having maintainers in the README — it makes it easier for
contributors to see who might be reviewing their contribution (and who to
bug on social media etc. to get it merged).

**Comment by drjwbaker** [comment]
Okay. I'll push ahead with this.

**Comment by drjwbaker** [comment]
Contributor info is done.

Author info, I've had a change of heart. SWC do this https://github.com/swcarpentry/shell-novice/blob/gh-pages/AUTHORS. We at the moment do this https://github.com/data-lessons/library-openrefine/network/members. I actually kind like what we do, because it leverages the services GitHub offers to represent authorship. It isn't perfect, but it feels more maintainable (if that is a word..) than a list of names. Happy as ever to be persuaded otherwise!

**Comment by mkuzak** [comment]
I also like the network view more.

**Comment by drjwbaker** [comment]
Closing this. If you'd rather we use an alternative way of displaying authors, please reopen to discuss further.
