### ISSUE TITLE
Setup menu item not displaying across lessons

### ISSUE THREAD

**Issue by ccronje** [data-lessons/librarycarpentry#9]
This issue follows on from discussion at https://github.com/data-lessons/library-openrefine/issues/42. All LC lessons are affected. Can @cmacdonell or someone please advise on how best to resolve across lessons? We would like the Setup menu item to be rendered as shown here http://swcarpentry.github.io/lesson-example/.

**Comment by mkuzak** [comment]
I forked swcarpentry/lesson-exmple https://github.com/data-lessons/lesson-example and plan to customise it with LC content. It then can be used in all lessons as a template.

**Comment by drjwbaker** [comment]
Is this not something we can fudge into the 'prerequisites' field per http://data-lessons.github.io/library-shell/ Or better still, put a link to a more detailed setup page in the 'prerequisites' field. It is front and centre and pretty hard to miss.

**Comment by ostephens** [comment]
Putting into pre-requisites looks like an easy short term fix, but I think @mkuzak is right we should adopt the latest template

**Comment by drjwbaker** [comment]
Okay. If the new template is easy to implement across lessons, I think we should proceed. If it will take some time though, hacking the preqs for now may get over some short term issues with minimal effort.

**Comment by mkuzak** [comment]
There is new template/example [data-lessons/lesson-example](https://data-lessons.github.io/lesson-example/) with Library Carpentry logo. I'm not sure how much we want to customise it. Any suggestions?

**Comment by drjwbaker** [comment]
http://data-lessons.github.io/library-data-intro/ has a 'cite' link. And a 'Contribute' page that is a little more LC 'as it is right now'-focused than the direct to contributing.md. Happy to drop the latter (though we need to retain the info somewhere), but I think the former is important: it should be clear from the landing page how to cite the lesson.

**Comment by mkuzak** [comment]
@drjwbaker  I updated CITING and CONTRIBUTING.md with LC specific content from library-data-intro lesson. I also added cite link in the footer.

**Comment by drjwbaker** [comment]
With a little of this http://data-lessons.github.io/library-shell/contribute/ sprinkled in, we'll be good to go! I like how the new template presents footers. Thanks for doing the heavy lifting on this @mkuzak!

**Comment by mkuzak** [comment]
In the old temple the contributing in footer leads to CONTRIBUTING.md an one in the navbar (top) leads to http://data-lessons.github.io/library-shell/contribute/
This is a bit confusing I think. Plus in new template there is no contributing in navbar.

**Comment by drjwbaker** [comment]
Sure. We just need to change the CONTRIBUTING.mds so that the Gitter, run a workshop stuff, is in there as well.

**Comment by mkuzak** [comment]
Great, can you edit it the way you want it?

**Comment by drjwbaker** [comment]
Done (I've made a pull request). Note that the link at 'raising an issue' is lesson specific, so someone (I did it last time, can do again) needs to make sure that the link goes to the right place for each lesson.

**Comment by mkuzak** [comment]
merged,
we need to keep this information about the link somewhere (unfortunately there are no comments in markdown :()

**Comment by drjwbaker** [comment]
I guess that is possible. I hacked it (and a few other places) that way because I didn't get Jekyll templating. Note, for example, I changed where the 'Contact' link goes on all the lesson pages, eg http://data-lessons.github.io/library-data-intro/, so it goes to the Gitter rather than SWC.
